name: Python CI

on:
  push:
    branches:
      - main
      - develop  # Include any branches you want to trigger the workflow
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        python3 -m pytest

    - name: Format code
      run: |
        black *.py
